name: obhains
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.4
  - attrs=21.2.0
  - black=19.10
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - click=8.0.3
  - mypy_extensions=0.4.3
  - openssl=1.1.1
  - pathspec=0.7.0
  - pip=21.2.4
  - python=3.9.7
  - regex=2021.8.3
  - setuptools=58.0.4
  - sqlite=3.36.0
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - wheel=0.37.0
  - pip:
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - gspread==4.0.1
    - gspread-dataframe==3.2.1
    - idna==3.3
    - numpy==1.21.4
    - oauthlib==3.1.1
    - pandas==1.3.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dateutil==2.8.2
    - pytz==2021.3
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - six==1.16.0
    - urllib3==1.26.7

